GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/620f9881dbe4032ff805e583

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

PATCH http://localhost:3000/subscribers/620f9dc67d055a09bf5cb593
Content-Type: application/json

{
    "name": "Awesome Person",
    "subscribedToChannel": "The Net Ninja"
}

###

DELETE http://localhost:3000/subscribers/620f9881dbe4032ff805e583